# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86b1698e9bf2d7079968bd29965d5e493360d4ede6c316c97371baaae894f3f4bb0277c361a9ba2ea837303c57e289865b9b3ae0f3d22670e3cfcf7e83b01551

test:
  secret_key_base: f1a1cf2607246e1430534ee7a7dcc2aa18aefab8cea48a7ac701afaa327bef8a591363c5834341f6ae678c0e63ac284f6385a07b8fe9c9377014285025b770f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
